app/models.py
from datetime import datetime
from . import db

class User(db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String(64), nullable=False, unique=True, index=True)
	username = db.Column(db.String(64), nullable=False, unique=True, index=True)
	is_admin = db.Column(db.Boolean)
	password_hash = db.Column(db.String(128))
	name = db.Column(db.String(64))
	location = db.Column(db.String(64))
	bio = db.Column(db.Text())
	member_sinze = db.Column(db.DateTime(), default=datetime.utcnow)
	avatar_hash = db.Column(db.String(32))

app/__init__.py
import os
from flask import Flask
from config import config
from flask_bootstrap import Bootstrap
from flask_sqlalchemt import SQLAlchemy

db = SQLAlchemy()

bootstrap = Bootstrap()

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])

	bootstrap.init_app(app)

	db.init_app(app)

	from .pages import pages as pages_blueprint
	app.register_blueprint(pages_blueprint)

	from .tools import tools as tools_blueprint
	app.register_blueprint(tools_blueprint)

	return app

app/pages/__init__.py
from flask import Blueprint

pages = Blueprint('pages', __name__)

from . import routes

app/pages/routes.py
from flask import render_template
from . import pages

@pages.route('/')
def index():
	return render_template('pages/index.html')

@pages.route('/user/<username>')
def user(username):
	return render_template('pages/user.html', username=username)

app/tools/__init__.py
from flask import Blueprint

tools = Blueprint('tools', __name__)

from . import routes

app/tools/routes.py
from flask import render_template
from . import tools

@tools.route('/')
def index():
	return render_template('talks/index.html')

@tools.route('/user/<username>')
def user(username):
	return render_template('tools/user.html', username=username)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Pages{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
  <a class="navbar-brand" href="{{ url_for('pages.index') }}">Pages</a>

  <ul class="nav navbar-nav">
    <li><a href="{{ url_for('pages.index') }}">Home</a></li>
    <li><a href="{{ url_for('pages.user', username='chooan') }}">Profile</a></li>
  </ul>
{% endblock %}

{% block content %}
<div class="container">
  {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/pages/index.html
{% extends "base.html" %}

{% block page_content %}
<h1>Hello World!</h1>
{% endblock %}

app/templates/pages/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
  <h1>Hello {{ username }}!</h1>
</div>
{% endblock %}